- block:
  # python-tempestconf's source code is placed by zuul at the same level
  # as refstack-client's code, so when the task changes dir to
  # refstack-client's folder, python-tempestconf is located one folder above
  - name: Install refstack-client and python-tempestconf
    shell: |
        set -ex
        export PATH=$PATH:/usr/local/sbin:/usr/sbin
        ./setup_env -c master -s ../python-tempestconf
    args:
        chdir: "{{ refstack_client_src_relative_path }}"
        executable: /bin/bash

  - name: Print Tempest account file
    shell: |
        set -ex
        cat /etc/openstack/accounts.yaml

  - name: Generate tempest configuration file
    shell: |
        set -ex
        export PATH=$PATH:/usr/local/sbin:/usr/sbin
        source .venv/bin/activate
        {{ source_credentials_commands }}
        printenv
        refstack-client config \
            --use-test-accounts /etc/openstack/accounts.yaml \
            --out /tmp/tempest.conf
    args:
        chdir: "{{ refstack_client_src_relative_path }}"
        executable: /bin/bash

  - name: Print generated tempest.conf
    shell: |
        set -ex
        cat /tmp/tempest.conf

  - name: Run refstack-client tests
    shell: |
        set -ex
        export PATH=$PATH:/usr/local/sbin:/usr/sbin
        source .venv/bin/activate
        printenv
        refstack-client test -c /tmp/tempest.conf \
            -v --test-list "https://refstack.openstack.org/api/v1/guidelines/2018.02/tests?target=platform&type=required&alias=true&flag=false"
    args:
        chdir: "{{ refstack_client_src_relative_path }}"
        executable: /bin/bash

  vars:
    refstack_client_src_relative_path: "{{ zuul.projects['git.openstack.org/openstack/refstack-client'].src_dir }}"
